feat: redisign signup page
xi-effect/xieffect-front pull request #116
Opened 2022-08-15 11:56 UTC by Gr1mmz

Задача https://www.notion.so/xieffect/8ec4951e48214f51b4fd17f7f669b009
Макет https://www.figma.com/file/Klu74VMZB28sukZ7ROGQ1r/Design?node-id=243%3A262

Полностью с нуля создал новую страницу регистрации. Добавил новый файл для формы регистрации (`SignupForm.tsx`), сами формы поделил на шаги и каждый положил в отдельный файл (`StepOneForm.tsx, StepTwoForm.tsx`) в соответствии с просьбой @unknownproperty.

На что по моему мнению стоит обратить особое внимание:
1. Верстка в файле `index.tsx`. Не совсем уверен в правильности, выглядит громоздко. Возможно есть способ ее ужать, но я не нашел такового.
2. В этом же файле `index.tsx` правильно ли реализовал респонсив. Использовал `useMediaQuery` от MUI, однако, чтобы он соответствовал макету, пришлось немного подогнать медиазапрос. При `max-width: 425px` он корректно срабатывал в инструментах разработчика только в десктоп-версии. В мобильной версии этот же брейкпоинт срабатывал на ~`370px`. Пришлось подобрать значение `max-width: 472px`, чтобы в мобильной версии отрабатывал брейкпоинт ровно на `425px`.
3. Реализация `handleSubmit` в файле `SignupForm.tsx` (функция `onSubmitHandler`). В `authorizationSt` есть функция `clickRegistrationButton`, которая, как я понял, как раз отвечает за регистрацию, однако при сабмите возвращается 400 ошибка `POST https://xieffect.ru:5000/reg/ 400`.
4. Обязательно нужно будет заменить в будущем на актуальное лого. Не стал грузить заново, т.к. в задаче по редизайну страницы входа @s2000promax уже создал компонент под лого.
5. После пуша последнего коммита при запуске `npm run dev` есть ошибка:
```js
error - unhandledRejection: Error: aborted
    at connResetException (node:internal/errors:691:14)
    at abortIncoming (node:_http_server:596:17)
    at socketOnClose (node:_http_server:590:3)
    at Socket.emit (node:events:402:35)
    at TCP.<anonymous> (node:net:687:12) {
  code: 'ECONNRESET'
```
Не понял, с чем связана, но, кажется, на работу компонента не влияет.

2022-08-15 12:18 UTC, niqzart commented
Ошибка в косоли — простой ресет соединения socketio, который случается периодически при рестарте приложения, смены интернет сети или обновлении сервера. Если она не появляется постоянно, то всё нормально. Я запусил у себя эту ветку, ошибки вроде нет

2022-08-15 12:27 UTC, niqzart requested changes
Ещё я не нашёл обработки ошибок, которые приходят с бэка. ~~В [документации](https://xieffect.ru:5000/doc/) они описаны, см. раздел reglog, запрос `/reg/`~~ (оказывается в доке почему-то их нет, добавлю!)

400ая скорее всего это `Malformed code (BadSignature)`. С ошибкой приходит JSON с единственным полем `a`, содержащим текст ошибки. Кстати, это сообщение также можно посмотреть в DevTools во вкладке `Network` и писать про возникающую ошибку уже зная сообщение

2022-08-15 12:27 UTC, niqzart commented on components/Signup/SignupForm.tsx
> +    code: yup.string().length(35).required(),
Там длинна кода не 35 символов, у них вовсе нет фиксированной длины

2022-08-15 12:27 UTC, niqzart commented on pages/signup/index.tsx
> +          <title>Ξffect | Регистрация</title>
На новых страницах стоит писать xi.effect

2022-08-15 12:46 UTC, niqzart commented
Вот новый вариант доков ответов на `/reg/`, загружу на сервер со следующим патчем
![image](https://user-images.githubusercontent.com/62603165/184637538-613ba300-b1ee-4eef-b157-9264f0ed19fd.png)

2022-08-17 11:07 UTC, Gr1mmz commented
Исправил замечания по ревью.

Главный вопрос - обработка ошибки, правильно ли сделано или нет. Меня смущает функция `clickRegistrationButton` 
в файле `authorizationSt`. Добавил кучу `if`, не придумал как сделать проще и красивее.

2022-08-17 12:25 UTC, niqzart reviewed
По моим правкам всё норм, особо плохого в if-ах тоже ничего не вижу

2022-08-17 12:25 UTC, niqzart approved these changes

2022-08-17 20:50 UTC, unknownproperty reviewed
Всё хорошо, но пара замечаний есть

2022-08-17 20:50 UTC, unknownproperty commented on components/Signup/SignupForm.tsx
> +    const [activeStep, setActiveStep] = useState<number>(0);
В таком случае можно явно не указывать типизацию, но это так, на будущее, TS сам понимает, что там 0 и что будут только number

2022-08-17 20:50 UTC, unknownproperty commented on components/Signup/StepOneForm.tsx
> +      <Box
В таком случае лучше использовать Stack

2022-08-17 20:50 UTC, unknownproperty commented on pages/signup/index.tsx
> +        <Box
Здесь тоже Stack

2022-08-17 20:50 UTC, unknownproperty commented on pages/signup/index.tsx
> +              <Box>
Чёт много Box, возможно, можно как-то переработать вёрстку

2022-08-17 21:06 UTC, niqzart commented on components/Signup/SignupForm.tsx
> +    const [activeStep, setActiveStep] = useState<number>(0);
Голосую за `explicit is better than implicit`, number там неплохо смотрится
(но это так, коммент, решать на фронте не мне)))

2022-08-18 08:32 UTC, Gr1mmz commented
Максимально постарался ужать верстку и использовать `<Stack>`. Изначально у меня с ним как-то не задалось, но сейчас разобрался, оказалось действительно проще и лаконичнее. Плюс убрал некоторые излишние стили и часть из них перенес из `sx` в атрибуты.

2022-08-18 11:54 UTC, merged