Tpanslate store to ts
xi-effect/xieffect-front pull request #124
Opened 2022-08-26 13:09 UTC by KhaninPasha0488

2022-09-01 17:46 UTC, Mr-G3ntl3man requested changes
`ts ignore` местами есть (грустно), по возможности если видишь и это не долго исправить сразу исправляй.

2022-09-01 17:46 UTC, Mr-G3ntl3man commented on components/Signup/Form.tsx
>  }
Что бы все что ты описал работало как и задумано нужно исправить типы или дописать если нету для каждого `tsx` где идет `inject `  , типы тебе уже известны.

```
interface ISignupForm {
  authorizationSt: AuthorizationSt;
  activeStep: number;
  setActiveStep: (value: number) => void;
}
```

По поводу как описать теперь `props` адекватного способа я не нашел но как рабочий использую это: 

```
const Form = inject('authorizationSt')(
  observer((props) => {
    
    const {
      authorizationSt,
      setActiveStep,
      activeStep
    }: ISignupForm = props;
    
      }),
);
```

Если ты опишешь это через React.FC или сразу в функции  то каждый раз где будет вызываться компонент будет требовать прокинуть стор и тд. в `props`.
Этот способ выглядит костыльно но работает и вызывает только одну проблему что если реально что-то нужно прокинуть в `props` он не подскажет.

Можешь поискать решение по лучше, найдешь пиши.
Описать нужно везде иначе толку от TS, помечу в остальных файлах тоже самое исправь.

2022-09-01 17:46 UTC, Mr-G3ntl3man commented on kit/Navigation/Sidebar/Sidebar.tsx
>              <IButton
Здесь тоже

```
type SidebarType = {
  rootStore?: any;
  communitiesMenuSt?: any;
  userSt?: any;
};
```

2022-09-01 17:46 UTC, Mr-G3ntl3man commented on pages/signin/index.tsx
> +    const { uiSt, userSt, authorizationSt } = props;
```
type SigninT = {
   uiSt: UiSt
   userSt: UserSt
  authorizationSt: AuthorizationSt
};


const Signin = inject(
  'uiSt',
  'userSt',
  'authorizationSt',
)(
  observer((props) => {

const {
  uiSt,
  userSt,
  authorizationSt
}: SigninT  = props 

}))
```

2022-09-01 17:46 UTC, Mr-G3ntl3man commented on store/community/communitiesMenuSt.ts
>      this.userCommunities = newArray.filter((item) => item.id !== lid);
это бы тоже исправить но я пока и сам не нашел структуру `userCommunities`

2022-09-12 10:24 UTC, KhaninPasha0488 commented on components/Signup/Form.tsx
>  }
В components/Signup/Form.tsx исправил

2022-09-12 10:30 UTC, KhaninPasha0488 commented on kit/Navigation/Sidebar/Sidebar.tsx
>              <IButton
В Saidbar.tsx   не получается, TS  всегда ругается .  Предлагаю отдельной таской  сделать, в этой таске и так много где изменения внес, очень много конфликтов приходится решать

2022-09-12 10:56 UTC, KhaninPasha0488 commented on pages/signin/index.tsx
> +    const { uiSt, userSt, authorizationSt } = props;
Добавил

2022-09-13 19:13 UTC, unknownproperty commented
Замержу

2022-09-13 19:13 UTC, merged