Invite link
xi-effect/xieffect-front pull request #159
Opened 2022-12-11 18:37 UTC by MartaGreen

1. Генерация ссылки-приглашения
2. Копирование ссылки при клике по кнопке

2022-12-11 21:44 UTC, unknownproperty requested changes
И у нас на барабане сектор - правки после ревью

Ну а если серьёзно, для первого раза сойдёт, расти уж точно есть куда, за этим ты и тут

Идею с анимацией меню я оценил, но в таком виде точно не пущу на прод, выглядит она всё же страшно. Как насчёт того, чтобы убрать шапку из анимации, чтобы она была статичной, и только контент выплывал справа?

А ещё ты сломала вёрстку))) 
Посравнивай то, что ты сделала с текущей версией

2022-12-11 21:44 UTC, unknownproperty commented on kit/UserProfile/Content.tsx
> +import { Box } from '@mui/system';
Не нужно использовать disable для eslint. Загугли ошибку и пойми что не так. PS обрати внимание на 3 строку

2022-12-11 21:44 UTC, unknownproperty commented on kit/UserProfile/Content.tsx
> +          mt: mobile700 ? '8px !important' : '',
Почему здесь возник important?

2022-12-11 21:44 UTC, unknownproperty commented on kit/UserProfile/ContentItems/Main.tsx
> +  const gInviteLink: () => string = () => {
лучше get, а не g, тк не понятно что это значит. Типизация здесь лишняя, превращает в кашу код

2022-12-11 21:44 UTC, unknownproperty commented on kit/UserProfile/ContentItems/Main.tsx
> +  const inviteId: string | null = profileSt.profile.code;
Перед функцией стоит добавить пробел, а то читабельность так себе

2022-12-11 21:44 UTC, unknownproperty commented on kit/UserProfile/ContentItems/Main.tsx
> +          mt: mobile700 ? '24px !important' : '32px !important',
Опять import, посмотри в браузере какое значение тебе мешает и попытайся найти первоисточник. Скорей всего дело в атрибуте spacing в Stack

2022-12-11 21:44 UTC, unknownproperty commented on kit/UserProfile/ContentItems/Main.tsx
> +            mt: '12px !important',
Тут тоже import

2022-12-11 21:44 UTC, unknownproperty commented on kit/UserProfile/ContentItems/Main.tsx
> +            mt: mobile700 ? '20px !important' : '',
Игра называется - найди import и исправь

2022-12-11 21:44 UTC, unknownproperty commented on kit/UserProfile/ContentItems/Main.tsx
> +            <Image src="/icons/copy.svg" width={26} height={26} />
Неожиданно иконку Copy ты используешь через Image. Добавь её в папку kit/MyIcons по аналогии с существующими иконками. Предварительно можно прогнать иконку через https://iconly.io/tools/svg-convert-stroke-to-fill

2022-12-11 21:44 UTC, unknownproperty commented on kit/UserProfile/ContentItems/Main.tsx
> +      <Snackbar open={isCopied} autoHideDuration={copySuccessDuration}>
Хорошая идея, но у нас уже есть рабочая система для подобных уведомлений, советую этот кусочек кода удалить и глобальным поиском найти и изучить нынешнюю систему - notistack

2022-12-11 21:44 UTC, unknownproperty commented on kit/UserProfile/HeaderMobile.tsx
> +          <div>{children}</div>
Не совсем понятно что тут делает эта div

2022-12-11 21:44 UTC, unknownproperty commented on kit/UserProfile/UserProfile.tsx
> +    console.log('close');
Консольку забыла

2022-12-11 21:44 UTC, unknownproperty commented on kit/UserProfile/UserProfile.tsx
> +                minWidth: 0,
Ам, а в чём смысл?

2022-12-13 18:17 UTC, mariik4 commented
На счет статичной шапки уточню. При выборе определенной "страницы" настроек бургер-меню меняется на кнопку назад с соответствующим названием настроек. Оставляем без анимации? 
<img width="320" alt="Снимок экрана 2022-12-13 в 19 14 10" src="https://user-images.githubusercontent.com/79785945/207412859-19fadf91-c870-4ebc-bbc5-d78a5eb5291e.png">
<img width="317" alt="Снимок экрана 2022-12-13 в 19 14 33" src="https://user-images.githubusercontent.com/79785945/207412866-71232b21-757b-4044-aa79-ffde8b8b7843.png">

2022-12-14 14:43 UTC, unknownproperty commented
Да, мне кажется так лучше, чтобы оно просто менялось и всё

2022-12-26 15:11 UTC, unknownproperty commented on kit/UserProfile/UserProfile.tsx
> +          // pt: mobile1400 ? '0px' : '64px',
тут забытый комментарий

2022-12-26 15:16 UTC, unknownproperty commented on kit/MyIcon/Editor/index.tsx
> +    copy: <Copy color={color} size={size} />,
А зачем нам лишний EditorIcon, давай напрямую использовать эту иконку

2022-12-26 15:19 UTC, unknownproperty commented on kit/MyIcon/Editor/Copy.tsx
> +const Copy: React.FC<CopyProps> = ({ color, size }: CopyProps) => (
Боюсь, что это не совсем то, как нужно создавать иконку, нам не нужны лишние пропсы и атрибуты нужна такая же как здесь https://github.com/xi-effect/xi.monorepo/blob/main/packages/pkg.icons.chat/Chat.tsx конструкция

2022-12-26 22:13 UTC, MartaGreen commented on kit/MyIcon/Editor/Copy.tsx
> +const Copy: React.FC<CopyProps> = ({ color, size }: CopyProps) => (
Уточню, нужно убрать React.FC, это поняла. 
Нужно ли изменить еще принимаемые значения как в примере?

```
export type ChatProps = {
  [key: string]: any;
};
```

Просто иконка принимает только значение size, которое задает сразу и width и height, если я сделаю как в примере, тогда нужно будет передавать два параметра.

2022-12-26 22:17 UTC, unknownproperty commented on kit/MyIcon/Editor/Copy.tsx
> +const Copy: React.FC<CopyProps> = ({ color, size }: CopyProps) => (
Тебе в целом стоит сделать компонент таким же как в примере, не только строка. Далее, при использовании иконки добавляешь 
`sx={{ fontSize: '24px' }}` как ни странно ,но это должно задавать размер иконке

2022-12-27 21:20 UTC, MartaGreen commented on kit/UserProfile/UserProfile.tsx
> +                minWidth: 0,
Забыла убрать (это из старого варианта кода)

2023-01-02 14:41 UTC, unknownproperty approved these changes

2023-01-02 21:00 UTC, unknownproperty commented
Замержу

2023-01-02 21:00 UTC, merged